MODULE geometry
  !---------------------------------------------------
  !  #[ Documentation
  !
  ! a module to define a datastructure to hold the satellite 
  ! and antenna geometry used by the rfscat simulation program,
  ! as well as the inversion and FOM results needed to asses 
  ! the quality of the system.
  !
  ! Written 2000,2001,2002 by Jos de Kloe, KNMI.
  !    
  ! Modifications;
  ! 07-May-2009 J. de Kloe  phase out all CPP definitions
  ! 12-May-2009 J. de Kloe  a number of smaller clean-ups
  ! 15-May-2009 J. de Kloe  moved the actual Pseudo_L1B file handling code
  !                         to its own module, to allow for easier 
  !                         implementation of different fileformats if needed.
  ! 20-May-2009 J. de Kloe  added FoM_skew to the wvc_type
  !
  !  #]
  !---------------------------------------------------
  !  #[ Modules used

  ! a module to define inversion subroutine and datatypes
  USE inversion, only:  inv_output_type, max_nr_of_views, &
       init_inv_output, undefined_pol
  USE numerics, only: r4_, missing_indicator_real_r4
  !  #]
  !  #[ Variables and types
  IMPLICIT NONE  ! no implicit variable typing
  public         ! make all variables public by default

  ! define the datastructure used to hold the geometry

  ! datatype to contain all data of one view
  TYPE view_type             
     real(r4_) :: antenna_dir  ! pointing dir. of the antenna
     real(r4_) :: theta        ! incidence angle of radar beam w.r.t. nadir
     real(r4_) :: sigma_0      ! normalised radar cross section
     ! this variable is needed in the polarimetric case to calculate kp
     real(r4_) :: sigma_0_vh   ! normalised radar cross section
     ! the next 3 are only used for the normalisation in the inversion
     ! routine, not to add noise to the simulated measurement !!
     real(r4_) :: kp_a         ! estimate of noise variance, a term
     real(r4_) :: kp_b         ! estimate of noise variance, b term
     real(r4_) :: kp_c         ! estimate of noise variance, c term
     ! the next 3 determine the noise on the simulated sigma_0 signals
     real(r4_) :: nr_noise_samples ! used to estimate the instrument noise 
     real(r4_) :: nr_samples       ! used to estimate the instrument noise 
     real(r4_) :: snr_prime        ! used to estimate the instrument noise 
     integer   :: polarisation ! record which polarisation was used
  END TYPE view_type
  
  ! datatype to contain all data of one wvc
  TYPE wvc_type 
     ! position of the wvc on the globe
     real(r4_) :: lat ! lattitude of wvc 
     real(r4_) :: lon ! longitude of wvc
     integer   :: nr_of_views  ! nr of views available for this wvc
     integer   :: node_nr      ! nr of the simulated node

     ! wind vector cell number (WVC) across the swath (1 is most left wvc)
     integer :: wvc_column_number
     integer :: wvc_row_number
     
     ! contains all data per view/measurement
     ! This is similar to the inv_input_type as defined in
     ! the inversion module
     TYPE(view_type), dimension(:), pointer :: view
     ! note max dimension for this one is max_nr_of_views
     ! as defined inside the inversion module

     ! input wind for this wvc (without geophysical noise)
     real(r4_) :: inp_u_orig
     real(r4_) :: inp_v_orig
     real(r4_) :: inp_speed_orig
     real(r4_) :: inp_dir_orig
     
     ! modified wind for this wvc, including geophysical noise (when applied)
     real(r4_) :: inp_u
     real(r4_) :: inp_v
     real(r4_) :: inp_speed
     real(r4_) :: inp_dir
     
     ! outputs generated by the inversion routine
     TYPE(inv_output_type) :: inv_output

     ! room to store the 2D MLE map and 2D prob map
!     real(r4_), dimension(:,:), pointer :: MLE_array
!     real(r4_), dimension(:,:), pointer :: probability_array
     ! typical dimension when allocated will be:
     ! 0:LUT_nr_windspeed_steps-1,0:nr_of_winddir_steps   -1 )

     ! index for solution closest to input wind vector
     integer :: index_closest
     
     ! fields to store the result for the different FOM definitions
     real(r4_) :: FOM_old
     real(r4_) :: FOM
     real(r4_) :: FOM_amb
     ! this one is not yet defined. Might be added in the future
     real(r4_) :: FOM_skew
  END TYPE wvc_type
    !  #]
  !--------------------------------
CONTAINS ! routines to handle the data in this module
  !--------------------------------
  subroutine init_view(view)
    !  #[
    type(view_type), intent(out) :: view

    view%antenna_dir      = missing_indicator_real_r4
    view%theta            = missing_indicator_real_r4
    view%sigma_0          = missing_indicator_real_r4
    view%sigma_0_vh       = missing_indicator_real_r4
    view%kp_a             = missing_indicator_real_r4
    view%kp_b             = missing_indicator_real_r4
    view%kp_c             = missing_indicator_real_r4
    view%nr_noise_samples = missing_indicator_real_r4
    view%nr_samples       = missing_indicator_real_r4
    view%snr_prime        = missing_indicator_real_r4
    view%polarisation     = undefined_pol

  end subroutine init_view
    !  #]
  !--------------------------------
  subroutine init_wvc(wvc)
    !  #[
    type(wvc_type), intent(out) :: wvc

    wvc%lat            = missing_indicator_real_r4
    wvc%lon            = missing_indicator_real_r4
    wvc%nr_of_views    = -1
    wvc%node_nr        = -1
    wvc%wvc_column_number = -1
    wvc%wvc_row_number    = -1
    nullify(wvc%view)
    wvc%inp_u_orig     = missing_indicator_real_r4
    wvc%inp_v_orig     = missing_indicator_real_r4
    wvc%inp_speed_orig = missing_indicator_real_r4
    wvc%inp_dir_orig   = missing_indicator_real_r4
    wvc%inp_u          = missing_indicator_real_r4
    wvc%inp_v          = missing_indicator_real_r4
    wvc%inp_speed      = missing_indicator_real_r4
    wvc%inp_dir        = missing_indicator_real_r4
    call init_inv_output(wvc%inv_output)
!    nullify(wvc%MLE_array)
!    nullify(wvc%probability_array)
    wvc%index_closest  = -1
    wvc%FOM_old        = missing_indicator_real_r4
    wvc%FOM            = missing_indicator_real_r4
    wvc%FOM_amb        = missing_indicator_real_r4
    wvc%FOM_skew       = missing_indicator_real_r4

  end subroutine init_wvc
    !  #]
  subroutine delete_wvc(wvc)
    !  #[
    type(wvc_type), intent(inout) :: wvc

    if (associated(wvc%view)) deallocate(wvc%view)
!    if (associated(wvc%MLE_array)) deallocate(wvc%MLE_array)
!    if (associated(wvc%probability_array)) deallocate(wvc%probability_array)

  end subroutine delete_wvc
    !  #]
  !--------------------------------
END Module geometry

